/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { UsageReportRequest, UsageReportValue, UsageSessionLogRequest, UsageSessionLogValue } from '@deepseek-ai/dsh-usage-dashboard/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7573616765 {
    report: (request: UsageReportRequest, signal?: AbortSignal) => Promise<RemoteResult<UsageReportValue>>
    sessionLog: (request: UsageSessionLogRequest, signal?: AbortSignal) => Promise<RemoteResult<UsageSessionLogValue>>
  }
  interface TypertRemoteMap {
    'usage/report': (request: UsageReportRequest, signal?: AbortSignal) => Promise<RemoteResult<UsageReportValue>>
    'usage/sessionLog': (request: UsageSessionLogRequest, signal?: AbortSignal) => Promise<RemoteResult<UsageSessionLogValue>>
  }
  interface TypertRemoteNamespaceMap {
    'usage': TypertRemoteNamespace$7573616765
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
