/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const JsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema))])
const _deepseek_ai_dsh_usage_dashboard_usage_report_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'timeZone': z.string().readonly(),
  'rangeStart': z.number().readonly().optional(),
  'rangeEnd': z.number().readonly().optional(),
})
const _deepseek_ai_dsh_usage_dashboard_usage_report_result$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'generatedAt': z.number().readonly(),
  'timeZone': z.string().readonly(),
  'rangeStart': z.number().readonly().optional(),
  'rangeEnd': z.number().readonly().optional(),
  'totals': z.object({
  'sessions': z.number().readonly(),
  'apiCalls': z.number().readonly(),
  'toolCalls': z.number().readonly(),
  'turns': z.number().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'totalTokens': z.number().readonly(),
  'costUsd': z.number().readonly(),
  'unpricedCalls': z.number().readonly(),
  'firstEventAt': z.number().readonly(),
  'lastEventAt': z.number().readonly(),
}).readonly(),
  'byHour': z.array(z.object({
  'hour': z.string().readonly(),
  'hourStart': z.number().readonly(),
  'apiCalls': z.number().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'totalTokens': z.number().readonly(),
  'costUsd': z.number().readonly(),
})).readonly(),
  'byModel': z.array(z.object({
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'apiCalls': z.number().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'totalTokens': z.number().readonly(),
  'costUsd': z.number().readonly(),
  'unpriced': z.boolean().readonly(),
})).readonly(),
  'bySession': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'createdAt': z.string().readonly(),
  'parentSession': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'apiCalls': z.number().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'totalTokens': z.number().readonly(),
  'costUsd': z.number().readonly(),
  'firstEventAt': z.number().readonly(),
  'lastEventAt': z.number().readonly(),
})).readonly(),
  'unknownModels': z.array(z.string()).readonly(),
  'pricing': z.record(z.string(), z.object({
  'cacheHitInputPerM': z.number().readonly(),
  'cacheMissInputPerM': z.number().readonly(),
  'outputPerM': z.number().readonly(),
  'peak': z.object({
  'cacheHitInputPerM': z.number().readonly(),
  'cacheMissInputPerM': z.number().readonly(),
  'outputPerM': z.number().readonly(),
}).readonly().optional(),
})).readonly().readonly(),
})
const _deepseek_ai_dsh_usage_dashboard_usage_sessionLog_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_usage_dashboard_usage_sessionLog_result$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'createdAt': z.string().readonly(),
  'truncated': z.boolean().readonly(),
  'events': z.array(z.object({
  'seq': z.number().readonly(),
  'time': z.number().readonly(),
  'type': z.string().readonly(),
  'data': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema))]).readonly(),
})).readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-usage-dashboard',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-usage-dashboard#usage/report',
      service: 'usageController',
      namespace: 'usage',
      method: 'report',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-usage-dashboard/types#UsageReportRequest',
            schema: _deepseek_ai_dsh_usage_dashboard_usage_report_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-usage-dashboard/types#UsageReportValue',
        schema: _deepseek_ai_dsh_usage_dashboard_usage_report_result$schema,
      },
      sourceLocation: {"file":"packages/usage/usage-dashboard/src/index.ts","line":49,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-usage-dashboard#usage/sessionLog',
      service: 'usageController',
      namespace: 'usage',
      method: 'sessionLog',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-usage-dashboard/types#UsageSessionLogRequest',
            schema: _deepseek_ai_dsh_usage_dashboard_usage_sessionLog_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-usage-dashboard/types#UsageSessionLogValue',
        schema: _deepseek_ai_dsh_usage_dashboard_usage_sessionLog_result$schema,
      },
      sourceLocation: {"file":"packages/usage/usage-dashboard/src/index.ts","line":72,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service backing the generated `ctx.remote.usage` namespace.",
        "summary": "Host service backing the generated `ctx.remote.usage` namespace.",
        "tags": [],
        "jsDoc": "/** Host service backing the generated `ctx.remote.usage` namespace. */",
        "key": "usageController",
        "exportName": "UsageController",
        "members": [
          {
            "kind": "method",
            "name": "report",
            "signature": "@Remote('report') report(request: UsageReportRequest, signal: AbortSignal): Promise<UsageReportValue>",
            "summary": "Compute the usage report for one Workspace over an optional window.",
            "jsDoc": "/**\n * Compute the usage report for one Workspace over an optional window.\n * @param request - target Workspace, caller-local time zone, and window.\n * @param signal - cancellation for persistence reads.\n * @returns totals, hourly series, per-model and per-session aggregates.\n * @throws RemoteError `gateway/bad-request` for an invalid time zone, or\n *   `usage/workspace-not-found` for an unknown Workspace.\n */"
          },
          {
            "kind": "method",
            "name": "sessionLog",
            "signature": "@Remote('sessionLog') sessionLog(request: UsageSessionLogRequest, signal: AbortSignal): Promise<UsageSessionLogValue>",
            "summary": "Read the raw event log of one Session accounted to a Workspace.",
            "jsDoc": "/**\n * Read the raw event log of one Session accounted to a Workspace.\n * @param request - Workspace and Session identities.\n * @param signal - cancellation for persistence reads.\n * @returns the Session's creation instant and its newest event rows.\n * @throws RemoteError `usage/workspace-not-found`,\n *   `usage/session-not-in-workspace`, or `usage/session-log-unavailable`\n *   on the documented conditions.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "JsonValue",
            "declaration": "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "UsageHourBucket",
            "declaration": "export interface UsageHourBucket {\n    readonly hour: string;\n    readonly hourStart: number;\n    readonly apiCalls: number;\n    readonly inputTokens: number;\n    readonly outputTokens: number;\n    readonly cacheReadTokens: number;\n    readonly cacheWriteTokens: number;\n    readonly totalTokens: number;\n    readonly costUsd: number;\n}"
          },
          {
            "name": "UsageLogEvent",
            "declaration": "export interface UsageLogEvent {\n    readonly seq: number;\n    readonly time: number;\n    readonly type: string;\n    readonly data: JsonValue;\n}"
          },
          {
            "name": "UsageModelPrice",
            "declaration": "export interface UsageModelPrice {\n    readonly cacheHitInputPerM: number;\n    readonly cacheMissInputPerM: number;\n    readonly outputPerM: number;\n    readonly peak?: { readonly cacheHitInputPerM: number; readonly cacheMissInputPerM: number; readonly outputPerM: number; };\n}"
          },
          {
            "name": "UsageModelRow",
            "declaration": "export interface UsageModelRow {\n    readonly provider: string;\n    readonly model: string;\n    readonly apiCalls: number;\n    readonly inputTokens: number;\n    readonly outputTokens: number;\n    readonly cacheReadTokens: number;\n    readonly cacheWriteTokens: number;\n    readonly totalTokens: number;\n    readonly costUsd: number;\n    readonly unpriced: boolean;\n}"
          },
          {
            "name": "UsageReportRequest",
            "declaration": "export interface UsageReportRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly timeZone: string;\n    readonly rangeStart?: number;\n    readonly rangeEnd?: number;\n}"
          },
          {
            "name": "UsageReportTotals",
            "declaration": "export interface UsageReportTotals {\n    readonly sessions: number;\n    readonly apiCalls: number;\n    readonly toolCalls: number;\n    readonly turns: number;\n    readonly inputTokens: number;\n    readonly outputTokens: number;\n    readonly cacheReadTokens: number;\n    readonly cacheWriteTokens: number;\n    readonly totalTokens: number;\n    readonly costUsd: number;\n    readonly unpricedCalls: number;\n    readonly firstEventAt: number;\n    readonly lastEventAt: number;\n}"
          },
          {
            "name": "UsageReportValue",
            "declaration": "export interface UsageReportValue {\n    readonly workspaceId: WorkspaceId;\n    readonly path: string;\n    readonly title: string;\n    readonly generatedAt: number;\n    readonly timeZone: string;\n    readonly rangeStart?: number;\n    readonly rangeEnd?: number;\n    readonly totals: UsageReportTotals;\n    readonly byHour: readonly UsageHourBucket[];\n    readonly byModel: readonly UsageModelRow[];\n    readonly bySession: readonly UsageSessionRow[];\n    readonly unknownModels: readonly string[];\n    readonly pricing: Readonly<Record<string, UsageModelPrice>>;\n}"
          },
          {
            "name": "UsageSessionLogRequest",
            "declaration": "export interface UsageSessionLogRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "UsageSessionLogValue",
            "declaration": "export interface UsageSessionLogValue {\n    readonly sessionId: SessionId;\n    readonly createdAt: string;\n    readonly truncated: boolean;\n    readonly events: readonly UsageLogEvent[];\n}"
          },
          {
            "name": "UsageSessionRow",
            "declaration": "export interface UsageSessionRow {\n    readonly sessionId: SessionId;\n    readonly createdAt: string;\n    readonly parentSession?: SessionId;\n    readonly apiCalls: number;\n    readonly inputTokens: number;\n    readonly outputTokens: number;\n    readonly cacheReadTokens: number;\n    readonly cacheWriteTokens: number;\n    readonly totalTokens: number;\n    readonly costUsd: number;\n    readonly firstEventAt: number;\n    readonly lastEventAt: number;\n}"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = Branded<'WorkspaceId'>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
